setwd("~/Desktop/Capstone")
twitter <- readLines(connection <- file("data/final/en_US/en_US.twitter.txt"), encoding = "UTF-8", skipNul = TRUE)
close(connection)
rm(connection)
blogs <- readLines(connection <- file("data/final/en_US/en_US.blogs.txt"), encoding = "UTF-8", skipNul = TRUE)
close(connection)
rm(connection)
news <- readLines(connection <- file("data/final/en_US/en_US.news.txt"), encoding = "UTF-8", skipNul = TRUE)
close(connection)
rm(connection)